import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { useStudent } from "../context/StudentContext";
import { sopAPI } from "../utils/api";
import toast from "react-hot-toast";

const TABS = ["Generate SOP", "Roast My SOP 🔥", "Improve SOP"];

export default function SOPPage() {
  const { student } = useStudent();
  const [activeTab, setActiveTab] = useState(0);
  const [sopText, setSopText] = useState("");
  const [generatedSOP, setGeneratedSOP] = useState(`Statement of Purpose — Computer Science

My journey in computer science began not in a classroom, but in a moment of frustration. During my second year of undergraduate studies, I watched a family member struggle to understand a complex medical report generated by an algorithm she couldn't question or appeal. That moment crystallised my purpose: to build AI systems that are not just powerful, but explainable and human-centred.

Over four years at my university, I have maintained a CGPA of 8.1 while leading three research-adjacent projects — a recommendation engine for 50,000 users, a fraud detection model deployed in a fintech pilot, and a natural language system for regional language processing. Each project taught me that the gap between academic AI and real-world impact is not technical — it is human.

I am drawn to the MS Computer Science programme because of its emphasis on responsible AI and human-computer interaction research. The work of Professor [X] on interpretable machine learning directly aligns with my thesis direction.

Post-graduation, I intend to return to India to build AI infrastructure for financial inclusion — a ₹20 trillion opportunity that remains largely unaddressed. I believe your programme will give me the tools, mentorship, and global perspective to lead that work.

I am ready. I look forward to contributing to your research community.`);
  const [roastResult, setRoastResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [typingDots, setTypingDots] = useState(0);
  const [streamingText, setStreamingText] = useState("");

  const generateFallbackSOP = (s, extra) => `
Statement of Purpose — ${s.preferredField || "Computer Science"}

My journey in ${s.preferredField || "technology"} began with a question I could not answer: how can data-driven systems genuinely improve human lives? Over the past four years of my undergraduate program, with a CGPA of ${s.gpa || "8.1"}, I have systematically pursued that question through coursework, research, and projects that bridge theory and real-world application.

${extra ? `${extra}\n\n` : ""}I am drawn to ${s.targetCountry || "Canada"} specifically because of its vibrant academic ecosystem, multicultural research environment, and its emphasis on applied innovation. The programme at your university directly aligns with my goal of building AI systems that scale human potential.

My undergraduate research on machine learning models for financial data prediction directly prepares me for graduate-level work. The rigour of the projects I led — from data collection to model deployment — has instilled in me a disciplined yet creative approach to problem-solving.

Post-graduation, I intend to contribute to India's rapidly expanding technology sector, bringing back cutting-edge research to solve problems at scale for a billion-plus users. I am confident that your programme will give me the tools, mentorship, and network to realise this vision.

I look forward to contributing to and learning from your academic community.
`.trim();

  const generateFallbackRoast = () => ({
    score: 62,
    grade: "C+",
    verdict: "This SOP is technically correct but dangerously forgettable.",
    issues: [
      { severity: "HIGH", text: "Opening line is cliché — 'journey began with a question' is used by 70% of applicants." },
      { severity: "HIGH", text: "No specific professors or research labs mentioned. Shows zero research about the university." },
      { severity: "MEDIUM", text: "The connection between undergrad work and graduate goals is weak and generic." },
      { severity: "MEDIUM", text: "Word 'contribute' used 3 times. Repetitive and lazy." },
      { severity: "LOW", text: "Third paragraph buries your strongest achievement. Lead with impact." },
    ],
    positives: [
      "Clear structure — intro, motivation, goals, conclusion.",
      "Relevant field experience is mentioned.",
      "Honest about post-graduation plans.",
    ],
    suggestion: "Start with a specific story or moment — a failure, a breakthrough, a problem you saw that nobody else noticed. That is how you stand out.",
  });

  const generateSOP = async () => {
    setLoading(true);
    setStreamingText("");
    setTypingDots(0);
    toast.dismiss();
    
    // Show typing animation for 3 seconds
    const typingInterval = setInterval(() => {
      setTypingDots(prev => (prev + 1) % 4);
    }, 500);
    
    try {
      const res = await sopAPI.generateSOP({
        name: student.name,
        gpa: student.gpa,
        field: student.preferredField,
        targetCountry: student.targetCountry,
        additionalInfo: sopText,
      });
      
      clearInterval(typingInterval);
      setTypingDots(0);
      
      // Stream the SOP word by word
      const words = res.data.sop.split(' ');
      let currentIndex = 0;
      const streamInterval = setInterval(() => {
        if (currentIndex < words.length) {
          setStreamingText(prev => prev + (prev ? ' ' : '') + words[currentIndex]);
          currentIndex++;
        } else {
          clearInterval(streamInterval);
          setGeneratedSOP(res.data.sop);
          setStreamingText("");
          toast.success("Your SOP is ready!");
        }
      }, 30);
    } catch {
      clearInterval(typingInterval);
      setTypingDots(0);
      
      const fallback = generateFallbackSOP(student, sopText);
      
      // Stream the fallback SOP word by word
      const words = fallback.split(' ');
      let currentIndex = 0;
      const streamInterval = setInterval(() => {
        if (currentIndex < words.length) {
          setStreamingText(prev => prev + (prev ? ' ' : '') + words[currentIndex]);
          currentIndex++;
        } else {
          clearInterval(streamInterval);
          setGeneratedSOP(fallback);
          setStreamingText("");
          toast.success("SOP generated! (Demo mode)");
        }
      }, 30);
    } finally { 
      setLoading(false); 
    }
  };

  const roastSOP = async () => {
    if (!sopText && !generatedSOP) { toast.error("Paste your SOP first!"); return; }
    setLoading(true);
    toast.loading("Admissions officer is reading your SOP...");
    try {
      const res = await sopAPI.roastSOP(sopText || generatedSOP);
      setRoastResult(res.data);
      toast.dismiss();
      toast.success("Your SOP has been roasted! 🔥");
    } catch {
      setRoastResult(generateFallbackRoast());
      toast.dismiss();
      toast.success("Roast complete! 🔥");
    } finally { setLoading(false); }
  };

  return (
    <div className="min-h-screen px-4 md:px-8 py-10 max-w-5xl mx-auto">
      <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }}>
        <h1 className="font-display text-3xl font-bold text-white mb-2">✍️ SOP Studio</h1>
        <p className="text-gray-400 mb-8">AI-powered Statement of Purpose generator and brutal feedback engine.</p>
      </motion.div>

      <div className="flex gap-2 mb-8 p-1 rounded-xl w-fit" style={{ background: "rgba(255,255,255,0.05)" }}>
        {TABS.map((tab, i) => (
          <button key={tab} onClick={() => setActiveTab(i)}
            className={`px-5 py-2.5 rounded-lg text-sm font-medium transition-all`}
            style={{ background: activeTab === i ? "#00D4B8" : "transparent", color: activeTab === i ? "#050E1F" : "#888" }}>
            {tab}
          </button>
        ))}
      </div>

      <AnimatePresence mode="wait">
        {activeTab === 0 && (
          <motion.div key="generate" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
            <div className="glass-card p-6 mb-4">
              <label className="text-sm text-gray-300 font-medium mb-3 block">
                Add any specific achievements, projects, or experiences you want included:
              </label>
              <textarea value={sopText} onChange={(e) => setSopText(e.target.value)} rows={5}
                placeholder="e.g. I built a recommendation system for 50,000 users. I interned at XYZ Corp. I published a paper on..."
                className="w-full px-4 py-3 rounded-xl text-white text-sm placeholder-gray-500 resize-none"
                style={{ background: "#112240", border: "1px solid rgba(0,212,184,0.2)" }} />
            </div>
            <button onClick={generateSOP} disabled={loading} className="btn-primary w-full py-3.5 text-base">
              {loading ? "Generating..." : "✨ Generate AI SOP"}
            </button>
            
            {typingDots > 0 && (
              <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="glass-card p-6 mt-6">
                <div className="text-gray-300 text-sm">
                  AI is writing your SOP{'.'.repeat(typingDots)}
                </div>
              </motion.div>
            )}
            
            {streamingText && (
              <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="glass-card p-6 mt-6">
                <div className="flex items-center justify-between mb-4">
                  <h3 className="font-semibold text-white">Your Generated SOP</h3>
                </div>
                <div className="text-gray-300 text-sm leading-relaxed whitespace-pre-wrap overflow-y-auto" style={{ maxHeight: "300px" }}>{streamingText}</div>
              </motion.div>
            )}
            
            {generatedSOP && !streamingText && (
              <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="glass-card p-6 mt-6">
                <div className="flex items-center justify-between mb-4 flex-wrap gap-2">
                  <h3 className="font-semibold text-white">Your Generated SOP</h3>
                  <div className="flex gap-2">
                    <button onClick={() => { navigator.clipboard.writeText(generatedSOP); toast.success("SOP copied!"); }}
                      className="text-sm px-3 py-1.5 rounded-lg" style={{ background: "rgba(0,212,184,0.2)", color: "#00D4B8" }}>
                      📋 Copy SOP
                    </button>
                    <button onClick={() => { setSopText(generatedSOP); setActiveTab(1); }}
                      className="text-sm px-3 py-1.5 rounded-lg" style={{ background: "rgba(255,107,107,0.2)", color: "#FF6B6B" }}>
                      Roast this SOP 🔥
                    </button>
                  </div>
                </div>
                <div className="text-gray-300 text-sm leading-relaxed whitespace-pre-wrap overflow-y-auto" style={{ maxHeight: "300px" }}>{generatedSOP}</div>
              </motion.div>
            )}
          </motion.div>
        )}

        {activeTab === 1 && (
          <motion.div key="roast" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
            <div className="glass-card p-6 mb-4">
              <label className="text-sm text-gray-300 font-medium mb-3 block">
                Paste your SOP here for brutal, honest feedback:
              </label>
              <textarea value={sopText} onChange={(e) => setSopText(e.target.value)} rows={8}
                placeholder="Paste your Statement of Purpose here..."
                className="w-full px-4 py-3 rounded-xl text-white text-sm placeholder-gray-500 resize-none"
                style={{ background: "#112240", border: "1px solid rgba(255,107,107,0.3)" }} />
            </div>
            <button onClick={roastSOP} disabled={loading}
              className="w-full py-3.5 text-base font-semibold rounded-xl transition-all"
              style={{ background: "linear-gradient(135deg, #FF6B6B, #FF4757)", color: "#fff" }}>
              {loading ? "Reading your SOP..." : "🔥 Roast My SOP"}
            </button>

            {roastResult && (
              <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mt-6 space-y-4">
                <div className="glass-card p-6 flex items-center gap-6" style={{ borderColor: "rgba(255,107,107,0.4)" }}>
                  <div className="text-center">
                    <div className="text-6xl font-bold font-display" style={{ color: roastResult.score > 70 ? "#06D6A0" : roastResult.score > 50 ? "#FFD166" : "#FF6B6B" }}>
                      {roastResult.score}
                    </div>
                    <div className="text-gray-400 text-sm">/ 100</div>
                    <div className="text-2xl font-bold mt-1" style={{ color: "#FFD166" }}>{roastResult.grade}</div>
                  </div>
                  <div>
                    <p className="text-white font-medium text-lg">"{roastResult.verdict}"</p>
                    <p className="text-gray-400 text-sm mt-2 italic">— AI Admissions Officer</p>
                  </div>
                </div>

                <div className="glass-card p-6">
                  <h3 className="font-semibold text-white mb-4">🚨 Critical Issues Found</h3>
                  <div className="space-y-3">
                    {roastResult.issues.map((issue, i) => (
                      <div key={i} className="flex items-start gap-3 p-3 rounded-lg"
                        style={{ background: issue.severity === "HIGH" ? "rgba(255,107,107,0.1)" : issue.severity === "MEDIUM" ? "rgba(255,209,102,0.1)" : "rgba(255,255,255,0.05)" }}>
                        <span className="text-xs font-bold px-2 py-0.5 rounded flex-shrink-0 mt-0.5"
                          style={{ background: issue.severity === "HIGH" ? "rgba(255,107,107,0.3)" : issue.severity === "MEDIUM" ? "rgba(255,209,102,0.3)" : "rgba(255,255,255,0.1)", color: issue.severity === "HIGH" ? "#FF6B6B" : issue.severity === "MEDIUM" ? "#FFD166" : "#888" }}>
                          {issue.severity}
                        </span>
                        <p className="text-gray-300 text-sm">{issue.text}</p>
                      </div>
                    ))}
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="glass-card p-5" style={{ borderColor: "rgba(6,214,160,0.3)" }}>
                    <h3 className="font-semibold text-white mb-3">✅ What Works</h3>
                    {roastResult.positives.map((p, i) => (
                      <p key={i} className="text-gray-300 text-sm mb-1.5">• {p}</p>
                    ))}
                  </div>
                  <div className="glass-card p-5" style={{ borderColor: "rgba(255,209,102,0.3)" }}>
                    <h3 className="font-semibold text-white mb-3">💡 AI Recommendation</h3>
                    <p className="text-gray-300 text-sm leading-relaxed">{roastResult.suggestion}</p>
                    <button onClick={() => setActiveTab(2)} className="btn-primary w-full mt-4 py-2 text-sm">
                      Fix My SOP →
                    </button>
                  </div>
                </div>
              </motion.div>
            )}

            {roastResult && (
              <div className="glass-card p-6 mt-4 text-center"
                style={{ background: "linear-gradient(135deg, rgba(255,107,107,0.08), rgba(155,89,255,0.08))", borderColor: "rgba(255,107,107,0.3)" }}>
                <h3 className="font-display text-xl font-bold text-white mb-2">Share Your Roast Score 🔥</h3>
                <p className="text-gray-400 text-sm mb-4">Challenge your friends to beat your score</p>
                <div className="inline-flex items-center gap-3 px-6 py-3 rounded-xl mb-5"
                  style={{ background: "rgba(255,107,107,0.15)", border: "1px solid rgba(255,107,107,0.4)" }}>
                  <span className="font-display text-4xl font-black" style={{ color: "#FF6B6B" }}>{roastResult.score}</span>
                  <div className="text-left">
                    <div className="text-white font-bold">/100</div>
                    <div className="text-gray-400 text-xs">Roast Score</div>
                  </div>
                  <span className="font-display text-3xl font-black" style={{ color: "#FFD166" }}>{roastResult.grade}</span>
                </div>
                <div className="flex gap-3 justify-center">
                  <button
                    onClick={() => {
                      const text = `My SOP got roasted ${roastResult.score}/100 (${roastResult.grade}) by StudyPath AI! "${roastResult.verdict}" Can you do better? Try StudyPath AI 🔥`;
                      navigator.clipboard.writeText(text);
                      alert("Copied! Share it on WhatsApp or Instagram 🔥");
                    }}
                    className="btn-primary px-6 py-2.5 text-sm">
                    📤 Copy & Share on WhatsApp
                  </button>
                  <button
                    onClick={() => window.location.reload()}
                    className="btn-secondary px-6 py-2.5 text-sm">
                    Try Again
                  </button>
                </div>
              </div>
            )}
          </motion.div>
        )}

        {activeTab === 2 && (
          <motion.div key="improve" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
            <div className="glass-card p-6 mb-4">
              <p className="text-gray-300 text-sm mb-4">Paste your SOP and describe what you want improved:</p>
              <textarea value={sopText} onChange={(e) => setSopText(e.target.value)} rows={6}
                placeholder="Paste your current SOP..."
                className="w-full px-4 py-3 rounded-xl text-white text-sm placeholder-gray-500 resize-none mb-4"
                style={{ background: "#112240", border: "1px solid rgba(0,212,184,0.2)" }} />
              <button onClick={generateSOP} disabled={loading} className="btn-primary w-full py-3 text-base">
                {loading ? "Improving..." : "🔧 Improve My SOP"}
              </button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
